import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const source=readFileSync(path.join(__dirname,'../public/app.js'),'utf8');
function helper(name:string,next:string){const from=source.indexOf(`async function ${name}(`),to=source.indexOf(`async function ${next}(`,from+1);assert.ok(from>=0&&to>from);return source.slice(from,to);}
function delayed(){let resolve!:(value:any)=>void;const promise=new Promise<any>(r=>resolve=r);return {resolve,promise};}
test('extension catalogs: newest refresh wins even when the old request finishes last',async()=>{const a=delayed(),b=delayed();let calls=0;const S:any={user:{id:'u'},project:{id:'p'},connected:true};const c:any={S,supports:()=>true,apiProject:()=>'',api:()=>++calls===1?a.promise:b.promise};vm.runInNewContext(helper('loadCatalog','openMenu'),c);const old=c.loadCatalog(true),fresh=c.loadCatalog(true);b.resolve({entries:['new']});await fresh;a.resolve({entries:['old']});await old;assert.deepEqual(S.catalog.entries,['new']);assert.equal(S.catalogRequest,null);});
test('extension catalogs cannot cross accounts even when project ids match',async()=>{const a=delayed();const S:any={user:{id:'u'},project:{id:'p'},connected:true};const c:any={S,supports:()=>true,apiProject:()=>'',api:()=>a.promise};vm.runInNewContext(helper('loadCatalog','openMenu'),c);const job=c.loadCatalog();S.user={id:'other'};a.resolve({entries:['private']});await job;assert.equal(S.catalog,undefined);});
test('extension opening shares a pending read instead of creating duplicate requests',async()=>{const a=delayed();let calls=0;const S:any={user:{id:'u'},project:{id:'p'},connected:true};const c:any={S,supports:()=>true,apiProject:()=>'',api:()=>{calls++;return a.promise;}};vm.runInNewContext(helper('loadCatalog','openMenu'),c);const first=c.loadCatalog(),second=c.loadCatalog();a.resolve({entries:[]});await Promise.all([first,second]);assert.equal(calls,1);});
for(const change of ['epoch','account','value'])test('access confirmation cannot authorize a changed '+change,async()=>{const d=delayed(),select={value:'full'},S:any={epoch:1,user:{id:'u'},accessConfirmed:false};const c:any={S,$:()=>select,markSettings:()=>{},confirmAction:()=>d.promise};const start=source.indexOf('async function selectAccess('),end=source.indexOf('\n}',start)+2;vm.runInNewContext(source.slice(start,end),c);const job=c.selectAccess();if(change==='epoch')S.epoch++;if(change==='account')S.user.id='other';if(change==='value')select.value='readonly';d.resolve(true);await job;assert.equal(S.accessConfirmed,false);assert.equal(select.value,change==='value'?'readonly':'full');});
test('same-scope full-access approval still authorizes explicitly confirmed access',async()=>{const select={value:'full'},S:any={epoch:1,user:{id:'u'}};const c:any={S,$:()=>select,markSettings:()=>{},confirmAction:async()=>true};const start=source.indexOf('async function selectAccess('),end=source.indexOf('\n}',start)+2;vm.runInNewContext(source.slice(start,end),c);await c.selectAccess();assert.equal(S.accessConfirmed,true);});
for(const change of ['edited','epoch','closed','account'])test('goal read does not overwrite '+change+' state',async()=>{const d=delayed(),input={value:''},dialog={open:false,showModal(){this.open=true;}},S:any={epoch:1,user:{id:'u'},project:{id:'p'},thread:{id:'t'},goalDraft:''};const c:any={S,goalTarget:null,$:(id:string)=>id==='goal-objective'?input:dialog,apiProject:()=>'',api:()=>d.promise,toast:()=>{}};vm.runInNewContext(helper('openGoal','openReferences'),c);const job=c.openGoal();if(change==='edited')input.value='my text';if(change==='epoch')S.epoch++;if(change==='closed')dialog.open=false;if(change==='account')S.user.id='other';d.resolve({goal:{objective:'old response'}});await job;assert.equal(input.value,change==='edited'?'my text':'');});
test('goal confirmation cannot write to the task selected while the confirmation was open',async()=>{const d=delayed();let writes=0;const input={value:'objective'},form:any={};const S:any={epoch:1,user:{id:'u'},project:{id:'p'},thread:{id:'t'}};const target={epoch:1,account:'u',projectId:'p',threadId:'t'};const c:any={S,goalTarget:target,$:(id:string)=>id==='goal-form'?form:input,action:(fn:Function)=>fn,confirmAction:()=>d.promise,api:async()=>writes++,renderAttachments:()=>{}};const line=source.split('\n').find(s=>s.startsWith("$('goal-form').onsubmit="));assert.ok(line);vm.runInNewContext(line!,c);const job=form.onsubmit();S.epoch++;S.thread.id='different';d.resolve(true);await assert.rejects(job,/任务已切换/);assert.equal(writes,0);});
test('new task confirmation cannot clear a newly selected task',async()=>{const d=delayed();let cleared=0;const S:any={epoch:1,capabilities:{createWithMessage:true},project:{kind:'project',root:'/fixture'}};const c:any={S,canStartTask:()=>true,confirmAction:()=>d.promise,clearConversation:()=>cleared++};const start=source.indexOf('async function startNewConversation('),end=source.indexOf('function selectedTaskStorageKey',start);vm.runInNewContext(source.slice(start,end),c);const job=c.startNewConversation();S.epoch++;d.resolve(true);await assert.rejects(job,/项目或任务已切换/);assert.equal(cleared,0);});
test('late admin config is not rendered after switching to a non-admin account',async()=>{const d=delayed(),dialog={open:false,showModal(){this.open=true;}};let fieldReads=0;const c:any={settingsSequence:0,S:{user:{id:'admin',admin:true}},$:(id:string)=>{if(id==='settings-dialog')return dialog;fieldReads++;return {};},api:()=>d.promise};const start=source.indexOf('async function openSettings('),end=source.indexOf('let usersSequence=',start);vm.runInNewContext(source.slice(start,end),c);const job=c.openSettings();c.S.user={id:'member',admin:false};d.resolve({transport:{type:'local'}});await job;assert.equal(fieldReads,0);});

test('diff tab selects exactly one panel and fetches diff once',async()=>{const nodes:any={};for(const name of ['quota','files','diff','browser'])nodes['panel-'+name]={hidden:false};const buttons=['quota','files','diff','browser'].map(panel=>({dataset:{panel},classList:{toggle(){}},setAttribute(){}}));let loads=0;const c:any={S:{},$:(id:string)=>nodes[id],document:{querySelectorAll:()=>buttons},loadDiff:async()=>loads++};const start=source.indexOf('async function switchPanel('),end=source.indexOf('\n',start);vm.runInNewContext(source.slice(start,end),c);await c.switchPanel('diff');assert.equal(c.S.panel,'diff');assert.equal(nodes['panel-diff'].hidden,false);assert.ok(['quota','files','browser'].every(n=>nodes['panel-'+n].hidden));assert.equal(loads,1);});
