import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { UserStore, Sessions, hashPassword, verifyPassword } from "../src/auth";
import { createApp } from "../src/server";
import { settings } from "../src/settings";
import { ProtectedConfigStore } from "../src/protected-config";
import { defaultConfig } from "../src/backend/config";

test("password hashing, session revocation, and serialized admin protection", async () => {
  const directory=await mkdtemp(path.join(os.tmpdir(),'webui-auth-'));
  const store=new UserStore(path.join(directory,'users.json'));await store.load();
  await assert.rejects(hashPassword('short'));
  const first=await store.upsert({username:'admin',password:'long-test-password',admin:true});
  assert.equal(await verifyPassword('long-test-password',store.users[0].passwordHash),true);
  assert.equal(await verifyPassword('wrong-password',store.users[0].passwordHash),false);
  assert.equal(await verifyPassword('password','scrypt$1$invalid'),false);
  const raw=await readFile(store.file,'utf8');assert.ok(!raw.includes('long-test-password'));
  const sessions=new Sessions();const issued=sessions.create(store.users[0]);assert.ok(sessions.get(issued.token,store));
  await store.upsert({id:first.id,username:'admin',admin:true,password:'another-long-password'});
  assert.equal(sessions.get(issued.token,store),null);
  await assert.rejects(store.upsert({id:first.id,username:'admin',admin:false}));
  await assert.rejects(store.upsert({username:'ADMIN',password:'long-test-password',admin:false}));
  const second=await store.upsert({username:'other',password:'long-test-password',admin:true});
  const results=await Promise.allSettled([store.upsert({id:first.id,username:'admin',admin:false}),store.upsert({id:second.id,username:'other',admin:false})]);
  assert.equal(results.filter(r=>r.status==='rejected').length,1);
  assert.equal(store.users.filter(u=>u.admin).length,1);
});
test("public binding requires explicit HTTPS origin; data-directory projects are rejected", async () => {
  assert.throws(()=>settings({CODEX_WEBUI_HOST:'0.0.0.0'}));
  assert.throws(()=>settings({CODEX_WEBUI_HOST:'0.0.0.0',CODEX_WEBUI_ORIGIN:'http://example.test'}));
  assert.throws(()=>settings({CODEX_WEBUI_ORIGIN:'https://example.test/path'}));
  assert.equal(settings({}).port,3210);
  const directory=await mkdtemp(path.join(os.tmpdir(),'webui-protected-'));
  const data=path.join(directory,'private');await mkdir(data);
  const config=new ProtectedConfigStore(path.join(data,'config.json'));await config.load();
  for(const root of [directory,data]) await assert.rejects(config.save({...defaultConfig(),projects:[{id:'private',name:'private',root,grants:[]}]}),/credential/);
});

test("production HTTP: auth, CSRF, origin, ACL, static compression, ETag, no secret disclosure", async t => {
  const directory=await mkdtemp(path.join(os.tmpdir(),'webui-http-'));
  const store=new UserStore(path.join(directory,'users.json'));
  const admin=await store.upsert({username:'admin',password:'long-test-password',admin:true});
  await store.upsert({username:'viewer',password:'long-test-password',admin:false});
  const origin='http://127.0.0.1:3210';
  const runtime=await createApp({host:'127.0.0.1',port:3210,origin,dataDir:directory,secureCookies:false});
  const server=runtime.app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));
  t.after(async()=>{runtime.close();server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));});
  const base=`http://127.0.0.1:${(server.address() as any).port}`;
  let cookie='',csrf='';
  const call=async(route:string,body?:any,method=body===undefined?'GET':'POST',extra:Record<string,string>={})=>{
    const response=await fetch(base+route,{method,headers:{...(cookie?{cookie}:{}),'content-type':'application/json',...(csrf?{'x-csrf-token':csrf}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body)});
    return response;
  };
  let response=await call('/api/codex/projects');assert.equal(response.status,401);
  response=await call('/api/login',{username:'admin',password:'long-test-password'},'POST',{origin:'https://evil.test'});assert.equal(response.status,403);
  response=await call('/api/login',{username:'admin',password:'long-test-password'});assert.equal(response.status,200);
  cookie=response.headers.get('set-cookie')!.split(';')[0];assert.match(response.headers.get('set-cookie')!,/httponly/i);assert.match(response.headers.get('set-cookie')!,/samesite=strict/i);
  const login=await response.json() as any;csrf=login.csrf;assert.ok(csrf);assert.equal(login.user.passwordHash,undefined);
  response=await call('/api/codex/admin/connect',{},'POST',{'x-csrf-token':''});assert.equal(response.status,403);
  response=await call('/api/codex/admin/connect',{},'POST',{origin:'https://evil.test'});assert.equal(response.status,403);
  response=await call('/api/admin/users');const users=await response.json();assert.equal(JSON.stringify(users).includes('scrypt'),false);
  response=await call('/api/codex/status');assert.equal((await response.json() as any).processPolicy,'attach-only');
  response=await call('/api/admin/users',{id:admin.id,username:'admin',password:'new-admin-password',admin:true},'PUT');assert.equal(response.status,200);
  response=await call('/api/session');assert.equal(response.status,401);
  response=await call('/api/login',{username:'viewer',password:'long-test-password'});assert.equal(response.status,200);cookie=response.headers.get('set-cookie')!.split(';')[0];csrf=(await response.json() as any).csrf;
  response=await call('/api/admin/users');assert.equal(response.status,403);
  response=await call('/api/codex/admin/config');assert.equal(response.status,403);
  response=await call('/api/codex/projects');assert.deepEqual(await response.json(),[]);
  response=await call('/api/codex/files?projectId=secret&path=auth.json');assert.ok([403,409].includes(response.status));
  response=await call('/api/logout',{});assert.equal(response.status,200);
  response=await call('/api/session');assert.equal(response.status,401);
  response=await call('/app.js',undefined,'GET',{'accept-encoding':'br'});assert.equal(response.status,200);assert.equal(response.headers.get('content-encoding'),'br');assert.match(response.headers.get('content-security-policy')!,/frame-ancestors 'none'/);
  const tag=response.headers.get('etag')!;assert.ok((await response.text()).includes('openStream'));
  response=await call('/app.js',undefined,'GET',{'if-none-match':tag});assert.equal(response.status,304);
  response=await call('/');const html=await response.text();assert.match(html,/app\.js\?v=[a-f0-9]{12}/);assert.match(html,/state\.js\?v=[a-f0-9]{12}/);
  response=await call('/src/auth.ts');assert.equal(response.status,404);
  response=await call('/users.json');assert.equal(response.status,404);
  response=await call('/healthz');assert.deepEqual(await response.json(),{ok:true});
});
